import type { ReportDefinition } from "./reports-catalog-base";

const FRAMING=(p:string)=>`UNFILTERED SERIES / MULTI-CHART SYNASTRY. ${p}

MULTI-CHART RULES:
- Accept 2–5 participants and analyze every unique pair.
- A→B means A's visiting planets in B's houses; B→A is the reverse.
- Never invent aspects, overlays, motives, history, diagnoses, crimes, or future events.
- Karmic, soulmate, fated, attraction and destiny language is symbolic interpretation only.
- Distinguish pair-specific signals from group patterns and preserve individual autonomy.
- Every substantive interpretation must be tied to supplied chart evidence.
- Use grounded language such as "this may suggest" and "this can manifest as".
- Exactly 31 chapters; chapter 30 contains exactly five numbered Brutal Truths; chapter 31 ends with: "Your chart does not give you an excuse. It gives you a mirror."
- Each chapter opens with an italic Chart Anchors line.`;

const specs:Array<{id:string;title:string;tagline:string;icon:string;premise:string;sections:string[]}>= [
["synastry-power-dynamics","THE POWER DYNAMICS FILE™","Where influence, autonomy, and control collide between two or more charts.","♜","Map symbolic power dynamics through Sun, Mars, Saturn, Pluto, angles and 1st/8th/10th-house overlays.",["Open the File","Person A and Power","Person B and Power","Additional Participants","The First Power Signature","Mutual Aspects","A→B House Power","B→A House Power","The Third-Chart Effect","Initiation and Resistance","Autonomy vs. Influence","Control vs. Cooperation","Pride and Recognition","Mars Under Pressure","Saturn and Rules","Pluto and Intensity","Sun and Identity","The 1st House Mirror","The 8th House Pressure Chamber","The 10th House Stage","Protection vs. Friction","What Each Person May Experience","The Group Pattern","Contradictions","What the Evidence Supports","Accountability","Mature Influence","Repairing Imbalances","When Nobody Bends","Five Brutal Truths","The Power You Choose to Build"]],
["synastry-emotional-weather","THE EMOTIONAL WEATHER REPORT™","The emotional climate created when two or more inner worlds meet.","☾","Examine Moon, Venus, Neptune and 4th/7th/12th-house overlays for emotional resonance, sensitivity and repair.",["Enter the Weather","Person A's Emotional Climate","Person B's Emotional Climate","Additional Emotional Voices","Moon-to-Moon","Moon and Venus","Moon and Saturn","Moon and Pluto","Neptune and Sensitivity","4th House Safety","7th House Bonding","12th House Absorption","What Feels Easy","Where Feelings Complicate","The Need to Be Understood","Withdrawal and Re-entry","Sensitivity Under Pressure","Timing Differences","Communication During Storms","The Group Climate","Absorption and Boundaries","Reassurance","Trust and Vulnerability","Contradictions","What the Charts Support","The Repair Conversation","Mature Emotional Pattern","Clearing the Weather","What Keeps Returning","Five Brutal Truths","The Forecast You Can Change"]],
["synastry-communication-code","THE COMMUNICATION CODE™","What the charts say about how people connect, clash, clarify, and misread.","☿","Analyze Mercury, Moon, Jupiter, Uranus and 3rd/9th/11th-house overlays for communication styles and repair.",["Decode the Signal","Person A's Communication System","Person B's Communication System","Additional Voices","Mercury-to-Mercury","Mercury-to-Moon","Mercury-to-Venus and Mars","Mercury-to-Jupiter","Mercury-to-Uranus","The 3rd House","The 9th House","The 11th House","Where Conversation Flows","Where Words Become Weapons","Silence and Withdrawal","Intellectual Chemistry","Different Definitions of Honesty","The Argument Loop","The Misunderstanding Pattern","Communication in the Group","Who Translates Whom","Where Ego Enters","Contradictions","What the Evidence Says","The Conversation Beneath the Conversation","Repair Protocol","Mature Communication","What Must Stop Being Assumed","The Choice to Clarify","Five Brutal Truths","The Code You Can Rewrite"]],
["synastry-attraction-architecture","THE ATTRACTION ARCHITECTURE™","The chart mechanics behind fascination, desire, chemistry, and distance.","♀","Explore Venus, Mars, Pluto, Sun, Ascendant and 5th/7th/8th-house overlays without asserting intent, consent or inevitability.",["Enter the Attraction Field","Person A's Desire Signature","Person B's Desire Signature","The Third-Chart Effect","Venus Meets Venus","Venus Meets Mars","Mars Meets Mars","Pluto and Intensity","Sun and Recognition","Ascendant Chemistry","5th House Spark","7th House Projection","8th House Depth","The First Pull","What Sustains Fascination","Projection","Distance and Pursuit","Desire Under Pressure","Boundaries and Consent","Group Attraction Pattern","Chemistry vs. Compatibility","Intensity vs. Stability","Contradictions","What the Charts Show","What They Do Not Prove","Mature Desire","Choice Beyond Chemistry","Keeping Attraction Healthy","The Integrated Pattern","Five Brutal Truths","The Attraction You Can Understand"]],
["synastry-karmic-patterns","THE KARMIC THREADS FILE™","Symbolic patterns of familiarity, repetition, and growth across two or more charts.","☊","Use Nodes, Saturn, Chiron, Pluto and 12th/8th/9th-house overlays to explore symbolic familiarity and growth.",["What Karmic Means Here","Person A's Growth Axis","Person B's Growth Axis","Additional Participant","North Node Contacts","South Node Symbolism","Saturn and Responsibility","Chiron and Tender Places","Pluto and Transformation","12th House Symbolism","8th House Symbolism","9th House Meaning","Familiarity","The Repeating Pattern","The Lesson Each Person May Trigger","The Group Theme","Where History Is Symbolic","Projection","What the Charts Cannot Prove","Responsibility Without Blame","Growth vs. Attachment","Contradictions","The Choice Point","Mature Growth","Breaking Repetition","Repair and Boundaries","What Becomes Possible","What Must Not Be Romanticized","The Integrated Lesson","Five Brutal Truths","The Thread You Choose to Continue"]],
["synastry-friendship-alliance","THE FRIENDSHIP ALLIANCE™","How two or more charts build trust, loyalty, laughter, and shared purpose.","♧","Analyze Mercury, Venus, Jupiter, Uranus, Sun and 3rd/5th/11th-house overlays for friendship chemistry.",["The Alliance Begins","Person A as a Friend","Person B as a Friend","The Group Member Who Changes Everything","Sun Recognition","Mercury and Conversation","Venus and Affection","Jupiter and Generosity","Uranus and Freedom","3rd House Friendship","5th House Play","11th House Belonging","Where Trust Builds","Loyalty Tested","Independence","Humor and Meaning","Competition and Comparison","Social Boundaries","Conflict Between Friends","The Group Dynamic","Who Connects Whom","Alliance as Team","Contradictions","What the Evidence Supports","What Could Fracture the Bond","Repairing Friendship","Healthy Independence","Shared Purpose","Mature Alliance","Five Brutal Truths","The Friendship You Can Choose"]],
["synastry-ambition-coalition","THE AMBITION COALITION™","What happens when two or more ambitions occupy the same room.","⚒","Examine Sun, Mars, Saturn, Jupiter, Midheaven and 2nd/6th/10th/11th-house overlays for collaboration and competition.",["The Coalition Forms","Person A's Ambition","Person B's Ambition","Additional Ambition","Sun and Visibility","Mars and Drive","Saturn and Standards","Jupiter and Expansion","Midheaven and Direction","2nd House Resources","6th House Work","10th House Reputation","11th House Networks","Who Leads","Who Challenges","Who Builds","Competition","Money and Resources","Definitions of Success","Group Strategy","When Collaboration Works","When Competition Takes Over","Contradictions","What the Evidence Supports","The Feedback Problem","Power and Responsibility","Mature Coalition","Dividing Roles","When Nobody Listens","Five Brutal Truths","The Work Worth Building Together"]],
["synastry-vulnerability-mirror","THE VULNERABILITY MIRROR™","Where closeness, defenses, trust, and emotional exposure meet.","◇","Use Moon, Venus, Neptune, Chiron, Pluto, Saturn and 4th/8th/12th-house overlays to explore vulnerability and repair.",["Before the Mirror","Person A's Vulnerability","Person B's Vulnerability","The Third Mirror","Moon and Safety","Venus and Receiving","Chiron and Tenderness","Saturn and Guarding","Pluto and Exposure","Neptune and Sensitivity","4th House Safety","8th House Exposure","12th House Vulnerability","What Opens the Door","What Closes It","Defenses Under Pressure","Trust Takes Time","Being Misread","Group Vulnerability","Uneven Emotional Labor","Boundaries","Intimacy Without Assumption","Contradictions","What the Evidence Supports","What It Does Not Prove","The Conversation Beneath","Repair After Exposure","Mature Vulnerability","Safety That Can Be Built","Five Brutal Truths","The Mirror You Can Face Together"]],
["synastry-conflict-repair","THE CONFLICT & REPAIR ATLAS™","Map the friction points—and the evidence-based routes back to connection.","⚔","Analyze Mars, Saturn, Uranus, Pluto, Mercury, Moon and 1st/6th/7th/8th-house overlays for conflict and repair.",["Read the Map","Person A Under Conflict","Person B Under Conflict","Additional Participant","Mars Triggers","Saturn Friction","Uranus Disruption","Pluto Intensity","Mercury During Conflict","Moon During Conflict","1st House Reactivity","6th House Irritation","7th House Opposition","8th House Pressure","The First Trigger","Escalation Sequence","Misunderstanding","Control and Defensiveness","Withdrawal and Pursuit","Conflict in the Group","Who Needs Space","Who Needs Resolution","What the Charts Support","What They Cannot Predict","Accountability","Repair Sequence","Boundaries and Reconnection","Mature Conflict","Choice Before Escalation","Five Brutal Truths","The Repair Atlas"]],
["synastry-constellation-between-us","THE CONSTELLATION BETWEEN US™","A whole-system reading of the bonds, roles, and patterns among multiple charts.","✦","Synthesize pairwise aspects, house overlays, domain signals, roles, autonomy, communication, trust, attraction, ambition and repair without a group verdict.",["Welcome to the Constellation","Person A's Orbit","Person B's Orbit","Person C and Beyond","Strongest Pairwise Signals","House Overlay Network","Attraction Network","Emotional Network","Communication Network","Trust Network","Power Network","Autonomy Network","Growth Network","Friendship Network","Ambition Network","Friction Network","Repair Network","Who Activates Whom","Where Roles Form","Where Alliances Form","Where Tensions Form","Shared Story","Individuality Inside the Group","Contradictions","Evidence We Can Use","What the Network Cannot Tell Us","Accountability","Healthy Boundaries","Mature Group Pattern","Five Brutal Truths","The Constellation You Choose"]]
];

export const SYNASTRY_EXPANSION_REPORTS: ReportDefinition[] = specs.map(([id,title,tagline,icon,premise,sections])=>({
  id,title,tagline,icon,category:"Unfiltered Series",adult:false,sections,targetWords:5000,
  systemFraming:FRAMING(premise),requiresPartner:true,estimatedPages:35,readingMinutes:25,
}));
